export enum RouterNames {
  HOME_PAGE = 'HOME_PAGE',

  REQUESTS_PAGE = 'REQUESTS_PAGE',

  ID_ROOT_STACK = 'ID_ROOT_STACK',

  CREATE_PAGE = 'CREATE_PAGE',
  CREATE_ORDER_PAGE = 'CREATE_ORDER_PAGE',
  CREATE_DELIVERY_PAGE = 'CREATE_DELIVERY_PAGE',
  USER_REQUESTS_PAGE = 'USER_REQUESTS_PAGE',
}
